# pull official base image
FROM node:18

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /theBookCooperUI/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install react-scripts@5.0.1 -g --silent

# add app
COPY . ./

# start app
CMD npm start

#FROM node:16.13.1-alpine as build
#RUN npm install -g serve # A simple webserver

#WORKDIR /usr/src/app
#COPY package*.json ./

#RUN npm install
#COPY . .

#RUN npm run build

#EXPOSE 80
#CMD ["serve", "-s", "build", "-l", "80"]
