FROM postgres

# Copy the SQL files to the container
COPY setup.sql /docker-entrypoint-initdb.d/setup.sql
COPY init_db.sql /docker-entrypoint-initdb.d/init_db.sql
COPY init_store_items.sql /docker-entrypoint-initdb.d/init_store_items.sql
